version: '3.9'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-newsletter}
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        command: postgres -c 'max_connections=1000'

        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data: